name: Run Cypress Component Tests

on:
  pull_request:
    branches: [develop]  # ⬅️ This means it only runs on PRs to 'develop'

jobs:
  cypress-run:
    runs-on: ubuntu-latest  # ⬅️ GitHub provides a free Linux server

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Start application
        run: npm start &  # ⬅️ Starts your app in the background

      - name: Wait for app to be ready
        run: npx wait-on http://localhost:3000  # ⬅️ Waits until app is up

      - name: Run Cypress tests
        uses: cypress-io/github-action@v6
        with:
          start: npm start
          wait-on: http://localhost:3000
